name: Run CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 15 * * 1"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.6"
      - name: Set up environment variables
        run: |
          echo "export LIBRARY_PATH=/opt/homebrew/lib" >> $GITHUB_ENV
          echo "export CPATH=/opt/homebrew/include" >> $GITHUB_ENV

      - name: Build
        run: go build -v ./...

      - name: go run
        run: make write
