name: Run CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 15 * * 1"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LIBRARY_PATH: /opt/homebrew/lib
      CPATH: /opt/homebrew/include
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.6"

      - name: Build
        run: go build -v ./...

      - name: go run
        run: make write
